resource management + changed model loader
sabauandrei98/RacingGame pull request #10
Opened 2019-04-18 11:17 UTC by tsboth

2019-04-18 11:58 UTC, krahen94 approved these changes
With a quick glance, it mostly looks good. Please insert more comments.

2019-04-18 11:58 UTC, krahen94 commented on Game/MyProject/Game/ModelLoader/ModelLoader.hpp
> +    static void processNode(aiNode*, const aiScene*, SceneNode*, const std::string&);
Do a ModelLoaderUtils namespace and add them there instead of static functions, they play better with multiple translation unity.

2019-04-18 11:58 UTC, krahen94 commented on Game/MyProject/Game/ResourceManager/ResourceManager.cpp
> +    scene = importer.GetOrphanedScene();
Please leave a comment here on why GetOrphanedScene is used so it's more obvious that you are doing your own custom deletion.

2019-04-18 11:58 UTC, krahen94 commented on Game/MyProject/Game/ResourceManager/ResourceManager.cpp
> +    CUSTOM_DELETER([](IvTexture* texture) {
I am not a fan of this naming convention, but hey.

2019-04-18 11:58 UTC, krahen94 commented on Game/MyProject/Game/SceneManagement/MeshInstance.hpp
> +    void setUniformValue(unsigned int, IvTexture*);
const Texture* ?

2019-04-22 06:45 UTC, raxvan commented on Game/MyProject/Game/ResourceManager/ResourceManager.hpp
> +    typedef std::map<std::string, ConstAiScenePtr>  StringToAiScene;
Never use std::list and std::map becuase they make the code slow. Always use std::unordered_map and std::vector instead.
https://www.youtube.com/watch?v=rX0ItVEVjHc

2019-04-22 06:46 UTC, raxvan reviewed
Some small change required.

2019-04-22 06:54 UTC, mircea-catana requested changes
change the enable_if and it's good for mergeing

2019-04-22 06:54 UTC, mircea-catana commented on Game/MyProject/Game/SceneManagement/CameraSceneNode.hpp
>  class CameraSceneNode : std::enable_shared_from_this<CameraSceneNode>, public SceneNode {
enable_shared_from_this is already in SceneNode, don't need it here as well

2019-04-24 02:49 UTC, mircea-catana approved these changes

2019-04-24 08:36 UTC, krahen94 approved these changes

2019-04-24 08:36 UTC, merged